### ISSUE TITLE
3-issue

### ISSUE THREAD

**Issue by Wjxfi** [amnesica/ClearClipboard#10]
https://github.com/x13a/Clipeus/issues/5
https://github.com/x13a/Clipeus/issues/6

Another issue:

Tiny app to clean clipboard.

No UI. Click on the app icon to clean clipboard. Also you can grant device & app notifications permission to clean clipboard automatically on screen off (long tap on the app icon).

Permissions

NOTIFICATION_LISTENER - receive screen off events (optional)

(https://github.com/x13a/Clipeus)

**Comment by amnesica** [comment]
@Wjxfi as the functionality of ClearClipboard is intended to be as minimal as it is now, there will most likely be no further functionality enhancements
